@extends('home')
@section('pageTitle')@include('blog::partials.blogPageTitle')@endsection
@section('pageDescription')@include('blog::partials.blogPageDescription')@endsection
@section('pageKeywords')@include('blog::partials.blogPageKeywords')@endsection
@section('breadcrumbs')@include('blog::partials.blogBreadcrumbs')@endsection
@section('image')@endsection
@section('aside')
    @include('blog::partials.blogMenu')
@endsection