<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreatePermissionTables extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $tableNames = config('permission.table_names');
        $columnNames = config('permission.column_names');

        Schema::create($tableNames['permissions'], function (Blueprint $table) {
            $table->increments('id');
            $table->text('name');
            // TODO Should NOT BE nullable in prod
            $table->string('guard_name')->nullable();
            $table->string('slug')->unique()->nullable();
            $table->string('description')->nullable();
            $table->string('model')->nullable();
            $table->timestamps();
            $table->softDeletes();
        });

        Schema::create($tableNames['roles'], function (Blueprint $table) {
            $table->increments('id');
            $table->text('name');
            // Stored as json
            $table->text('title');
            // Stored as json
            $table->text('description');
            $table->tinyInteger('level')->nullable();
            // TODO Should NOT BE nullable in prod
            $table->string('guard_name')->default('web');
            $table->string('slug')->unique()->nullable();
            $table->timestamps();
            $table->softDeletes();
        });
        Schema::create($tableNames['model_has_permissions'], function (Blueprint $table) use ($tableNames, $columnNames) {
            $table->unsignedInteger('permission_id');

            $table->string('model_type');
            $table->unsignedBigInteger($columnNames['model_morph_key']);
            $table->index([$columnNames['model_morph_key'], 'model_type', ]);

            $table->foreign('permission_id')
                ->references('id')
                ->on($tableNames['permissions'])
                ->onDelete('cascade');

            $table->primary(['permission_id', $columnNames['model_morph_key'], 'model_type'],
                    'model_has_permissions_permission_model_type_primary');
        });

        Schema::create($tableNames['model_has_roles'], function (Blueprint $table) use ($tableNames, $columnNames) {
            $table->unsignedInteger('role_id');

            $table->string('model_type');
            $table->unsignedBigInteger($columnNames['model_morph_key']);
            $table->index([$columnNames['model_morph_key'], 'model_type', ]);

            $table->foreign('role_id')
                ->references('id')
                ->on($tableNames['roles'])
                ->onDelete('cascade');

            $table->primary(['role_id', $columnNames['model_morph_key'], 'model_type'],
                    'model_has_roles_role_model_type_primary');
        });

        Schema::create($tableNames['role_has_permissions'], function (Blueprint $table) use ($tableNames) {
            $table->unsignedInteger('permission_id');
            $table->unsignedInteger('role_id');

            $table->foreign('permission_id')
                ->references('id')
                ->on($tableNames['permissions'])
                ->onDelete('cascade');

            $table->foreign('role_id')
                ->references('id')
                ->on($tableNames['roles'])
                ->onDelete('cascade');

            $table->primary(['permission_id', 'role_id']);
            
            app('cache')
                ->store(config('permission.cache.store') != 'default' ? config('permission.cache.store') : null)
                ->forget(config('permission.cache.key'));
        });
        /***
        DB::table('roles')->insert(
            array(
                array('name' => 'superadmin','title' => '{"en":"Super administrator", "fr":"Super administrateur", "nl":"Superbeheerder", "de":"Super Administrator", "es":"Super administrador", "it":"Super amministratore", "ru":"Супер администратор", "pt":"Super administrador"}','description' => '{"en":"The super administrator has all privileges and the maximum level of authorization, that is to say 5.","fr":"Le super administrateur a tous les pouvoirs et le niveau maximal d\'autorisation, soit 5.","nl":"De superbeheerder heeft alle bevoegdheden en het maximale autorisatieniveau, dat wil zeggen 5.","de":"Der Superadministrator verfügt über alle Befugnisse und die maximale Berechtigungsebene, dh 5.","es":"El superadministrador tiene todos los poderes y el máximo nivel de autorización, es decir 5.","it":"Il super amministratore ha tutti i poteri e il livello massimo di autorizzazione, 5.","ru":"Супер администратор обладает всеми полномочиями и максимальным уровнем авторизации, то есть 5.","pt":"O superadministrador tem todos os poderes e o nível máximo de autorização, isto é, 5."}','guard_name' => 'superadmin','slug' => NULL,'created_at' => NULL,'updated_at' => '2019-01-27 16:09:22','deleted_at' => NULL),
                array('name' => 'admin','title' => '{"en":"Administrator", "fr":"Administrateur", "nl":"Beheerder", "de":"Administrator", "es":"Administrador", "it":"Amministratore", "ru":"администратор", "pt":"Administrador"}','description' => '{"en":"An administrator has the privileges required to administer the database as a whole, but not the configuration of the platform.","fr":"Un administrateur dispose des privilèges requis pour administrer la base de données dans son ensemble, mais pas la configuration de la plateforme.","nl":"Een beheerder heeft de rechten die vereist zijn om de database te beheren, maar niet de configuratie van het platform.","de":"Ein Administrator verfügt über die erforderlichen Berechtigungen zum Verwalten der Datenbank als Ganzes, nicht jedoch für die Konfiguration der Plattform.","es":"Un administrador tiene los privilegios necesarios para administrar la base de datos en su totalidad, pero no la configuración de la plataforma.","it":"Un amministratore ha i privilegi necessari per amministrare il database nel suo complesso, ma non la configurazione della piattaforma.","ru":"Администратор обладает правами, необходимыми для администрирования базы данных в целом, но не настройки платформы.","pt":"Um administrador tem os privilégios necessários para administrar o banco de dados como um todo, mas não a configuração da plataforma."}','guard_name' => 'admin','slug' => NULL,'created_at' => NULL,'updated_at' => '2019-01-27 16:09:33','deleted_at' => NULL),
                array('name' => 'manager','title' => '{"en":"Department manager","fr":"Responsable de département","nl":"Afdelingsmanager","de":"Abteilungsleiter","es":"Gerente de departamento","it":"Responsabile di reparto","ru":"Заведующий отделом","pt":"Gerente de departamento"}','description' => '{"en":"The department manager is the equivalent of a department manager (front-end management, application sections based on roles). Level 3 Privileges.","fr":"Le gestionnaire de département est l\'équivalent d\'un responsable de département (gestion du front-end, des sections de l\'application en fonction des rôles). Privilèges de niveau 3.","nl":"Een afdelingsmanager is het equivalent van een afdelingsmanager (front-end management, toepassingssecties op basis van rollen). Privileges van niveau 3.","de":"Der Abteilungsleiter entspricht einem Abteilungsleiter (Front-End-Management, auf Rollen basierende Anwendungsabschnitte). Stufe 3 Berechtigungen.","es":"El gerente de departamento es el equivalente de un gerente de departamento (administración de front-end, secciones de aplicación basadas en roles). Nivel 3 Privilegios.","it":"Il responsabile di reparto è l\'equivalente di un responsabile di reparto (gestione front-end, sezioni dell\'applicazione in base ai ruoli). Privilegi di livello 3.","ru":"Менеджер отдела является эквивалентом менеджера отдела (интерфейсное управление, разделы приложений на основе ролей). Уровень 3 Привилегии.","pt":"O gerente de departamento é o equivalente a um gerente de departamento (gerenciamento de front-end, seções de aplicativos baseadas em funções). Privilégios de nível 3."}','guard_name' => 'manager','slug' => NULL,'created_at' => NULL,'updated_at' => '2019-01-27 16:09:43','deleted_at' => NULL),
                array('name' => 'unverified','title' => '{"en":"Unverified user","fr":"Utilisateur non vérifié","nl":"niet-geverifieerde gebruiker","de":"Ungeprüfter Benutzer","es":"Usuario no verificado","it":"Utente non verificato","ru":"Неподтвержденный пользователь","pt":"usuário não verificado"}','description' => '{"en":"An unverified user does not access any of the features of the application. He must verify his email address in order to access Level 2 features.","fr":"Un utilisateur non vérifié n\'accède à aucune des fonctions de l\'application. Il doit vérifier son adresse de courrier électronique pour pouvoir accéder aux fonctions de niveau 2.","nl":"Een niet-geverifieerde gebruiker heeft geen toegang tot een van de functies van de toepassing. Hij moet zijn e-mailadres verifiëren om toegang te krijgen tot niveau 2-functies.","de":"Ein ungeprüfter Benutzer greift nicht auf die Funktionen der Anwendung zu. Er muss seine E-Mail-Adresse bestätigen, um auf verifizierte Benutzer der Stufe 2.","es":"Un usuario no verificado no accede a ninguna de las funciones de la aplicación. Debe verificar su dirección de correo electrónico para acceder a las funciones de Nivel 2.","it":"Un utente non verificato non accede a nessuna delle funzionalità dell\'applicazione. Deve controllare il suo indirizzo e-mail per accedere alle funzionalità di Livello 2.","ru":"Неподтвержденный пользователь не имеет доступа к каким-либо функциям приложения. Он должен проверить свой адрес электронной почты, чтобы получить доступ к функциям уровня 2.","pt":"Um usuário não verificado não acessa nenhum dos recursos do aplicativo. Ele deve verificar seu endereço de e-mail para acessar os recursos do Nível 2."}','guard_name' => 'web','slug' => NULL,'created_at' => NULL,'updated_at' => '2019-01-26 17:28:50','deleted_at' => NULL),
                array('name' => 'verified','title' => '{"en":"Verified user","fr":"Utilisateur vérifié","nl":"Geverifieerde gebruiker","de":"Geprüfter Benutzer","es":"Usuario verificado","it":"Utente verificato","ru":"Проверенный пользователь","pt":"Usuário verificado"}','description' => '{"en":"A user is said to be "verified" because he has confirmed his email address or other useful information. He is therefore authorized to access level 2 functions.","fr":"Un utilisateur est dit "vérifié", parce qu\'il a confirmé son adresse de courriel ou d\'autres informations utiles. Il est donc autorisé à accéder aux fonctions de niveau 2.","nl":"Een gebruiker wordt "geverifieerd" omdat hij zijn e-mailadres heeft bevestigd. Hij is daarom gemachtigd om toegang te krijgen tot niveau 2-functies.","de":"Ein Benutzer wird als "verifiziert" bezeichnet, weil er seine E-Mail-Adresse bestätigt hat. Er ist daher berechtigt, auf Funktionen der Ebene 2 zuzugreifen.","es":"Se dice que un usuario está "verificado" porque ha confirmado su dirección de correo electrónico. Por lo tanto, está autorizado para acceder a las funciones de nivel 2.","it":"Si dice che un utente è "verificato" perché ha confermato il suo indirizzo email. È quindi autorizzato ad accedere alle funzioni di livello 2.","ru":"Пользователь считается «проверенным», потому что он подтвердил свой адрес электронной почты или другую полезную информацию. Поэтому он имеет право доступа к функциям уровня 2.","pt":"Um usuário é considerado "verificado" porque confirmou seu endereço de e-mail ou outras informações úteis. Ele está, portanto, autorizado a acessar funções de nível 2."}','guard_name' => 'web','slug' => NULL,'created_at' => NULL,'updated_at' => '2019-01-26 17:32:13','deleted_at' => NULL),
                array('name' => 'candidate','title' => '{"en":"Candidate for membership","fr":"Candidat à l\'affiliation","nl":"Kandidaat voor aansluiting","de":"Kandidat für die Mitgliedschaft","es":"Candidato a la afiliación","it":"Candidato per affiliazione","ru":"Кандидат в члены","pt":"Candidato para afiliação"}','description' => '{"en":"This role is automatically assigned to all Level 2 users (access to e-commerce).","fr":"Rôle automatiquement assigné à tous les utilisateurs de niveau 2 permettant l\'accès à la section marchande.","nl":"Deze rol wordt automatisch toegewezen aan alle gebruikers van Level 2 (toegang tot e-commerce).","de":"Diese Rolle wird automatisch allen Benutzern der Stufe 2 zugewiesen (Zugriff auf E-Commerce).","es":"Este rol se asigna automáticamente a todos los usuarios de Nivel 2 (acceso al comercio electrónico).","it":"Questo ruolo viene assegnato automaticamente a tutti gli utenti di Livello 2 (accesso all\'e-commerce).","ru":"Эта роль назначается автоматически всем пользователям уровня 2 (доступ к электронной торговле).","pt":"Esta função é atribuída automaticamente a todos os usuários do Nível 2 (acesso ao e-commerce)."}','guard_name' => 'web','slug' => NULL,'created_at' => NULL,'updated_at' => '2019-01-26 17:47:53','deleted_at' => NULL),
                array('name' => 'vendor','title' => '{"en":"Translator","fr":"Traducteur","nl":"Vertaler","de":"Übersetzer","es":"Traductor","it":"Traduttore","ru":"переводчик","pt":"Tradutor"}','description' => '{"en":"The unverified translator role, alias linguist, is assigned upon registration from the registration form.","fr":"Le rôle de traducteur alias linguiste, est assigné dès l\'inscription depuis le formulaire d\'enregistrement.","nl":"De rol van vertaler, alias linguïst, wordt toegekend bij registratie op het registratieformulier.","de":"Die Übersetzerrolle, Alias-Linguist, wird bei der Registrierung über das Registrierungsformular zugewiesen.","es":"El rol de traductor, alias lingüista, se asigna al registrarse desde el formulario de registro.","it":"Il ruolo di traduttore, alias linguista, viene assegnato al momento della registrazione dal modulo di registrazione.","ru":"Роль переводчика, псевдоним лингвиста, назначается при регистрации из регистрационной формы.","pt":"A função de tradutor, alias lingüista, é atribuída no registro do formulário de inscrição."}','guard_name' => 'web','slug' => NULL,'created_at' => NULL,'updated_at' => '2019-01-26 18:35:18','deleted_at' => NULL),
                array('name' => 'buyer','title' => '{"en":"Customer","fr":"Client","nl":"Klant","de":"Kunde","es":"Cliente","it":"Donne d\'Ordine","ru":"клиент","pt":"Cliente"}','description' => '{"en":"The "buyer" is assigned when creating the user account if this option is selected.","fr":"Le rôle "entreprise non vérifiée" est le nom du crédit du compte d\'utilisateur si cette option est disponible.","nl":"De rol "niet-geverifieerd bedrijf" wordt toegewezen bij het maken van het gebruikersaccount als deze optie is geselecteerd.","de":"Die Rolle "nicht verifiziertes Unternehmen" wird bei der Erstellung des Benutzerkontos zugewiesen, wenn diese Option ausgewählt ist.","es":"La función "empresa no verificada" se asigna al crear la cuenta de usuario si se selecciona esta opción.","it":"Il ruolo "azienda non verificata" viene assegnato quando si crea l\'account utente se questa opzione è selezionata.","ru":"Роль «непроверенная компания» назначается при создании учетной записи пользователя, если выбран этот параметр.","pt":"A função "empresa não verificada" é atribuída ao criar a conta do usuário, se essa opção for selecionada."}','guard_name' => 'web','slug' => NULL,'created_at' => NULL,'updated_at' => '2019-01-26 18:48:22','deleted_at' => NULL),
                array('name' => 'dtper','title' => '{"en":"DTP specialist","fr":"Infographiste / Spécialiste PAO","nl":"Grafisch ontwerper","de":"Grafikdesigner","es":"Diseñador gráfico","it":"Specialista infografica","ru":"Специалист по инфографике","pt":"Designer gráfico"}','description' => '{"en":"The role of graphic designer is assigned at the time of registration, if the new user selects this option.","fr":"Le rôle d\'infographiste est assigné au moment de l\'enregistrement, si le nouvel utilisateur sélectionne cette option.","nl":"De rol van grafisch ontwerper wordt op het moment van registratie toegewezen indien de nieuwe gebruiker deze optie selecteert.","de":"Die Rolle des Grafikdesigners wird zum Zeitpunkt der Registrierung zugewiesen, wenn der neue Benutzer diese Option auswählt.","es":"El rol de diseñador gráfico se asigna en el momento del registro, si el nuevo usuario selecciona esta opción.","it":"Il ruolo di graphic designer è assegnato al momento della registrazione, se il nuovo utente seleziona questa opzione.","ru":"Роль графического дизайнера назначается во время регистрации, если новый пользователь выбирает эту опцию.","pt":"A função de designer gráfico é atribuída no momento do registro, se o novo usuário selecionar essa opção."}','guard_name' => 'web','slug' => NULL,'created_at' => NULL,'updated_at' => '2019-01-26 18:42:34','deleted_at' => NULL),
                array('name' => 'translator-verified','title' => '{"en":"Verified translator","fr":"Traducteur vérifié","nl":"Geverifieerde vertaler","de":"Überprüfter Übersetzer","es":"Traductor verificado","it":"Traduttore verificato","ru":"Проверенный переводчик","pt":"Tradutor confirmado"}','description' => '{"en":"The role of verified translator is granted after verification of the profile as part of the subscription subscription.","fr":"Le rôle de traducteur vérifié est octroyé après vérification du profil dans le cadre de la souscription d\'un abonnement.","nl":"De rol van geverifieerde vertaler wordt verleend na verificatie van het profiel als onderdeel van het abonnementsabonnement.","de":"Die Rolle des verifizierten Übersetzers wird nach der Verifizierung des Profils als Teil des Abonnements gewährt.","es":"El rol de traductor verificado se otorga después de la verificación del perfil como parte de la suscripción.","it":"Il ruolo del traduttore verificato è concesso dopo la verifica del profilo come parte dell\'abbonamento all\'abbonamento.","ru":"Роль проверенного переводчика предоставляется после проверки профиля в рамках подписки.","pt":"A função do tradutor verificado é concedida após a verificação do perfil como parte da assinatura."}','guard_name' => 'web','slug' => NULL,'created_at' => '2019-01-26 18:53:18','updated_at' => '2019-01-26 18:53:18','deleted_at' => NULL),
                array('name' => 'buyer-verified','title' => '{"en":"Verified company","fr":"Entreprise vérifiée","nl":"Geverfieerde onderneming","de":"Überprüfte Gesellschaft","es":"Empresa verificada","it":"Azienda verificata","ru":"Проверенная компания","pt":"Empresa verificada"}','description' => '{"en":"The "verified company" role is assigned when subscribing to a subscription if the company meets the verification criteria.","fr":"Le rôle "entreprise vérifiée" est assigné lors de la souscription d\'un abonnement si l\'entreprise répond aux critères de vérification.","nl":"De rol "geverifieerd bedrijf" wordt toegewezen bij het abonneren op een abonnement als het bedrijf aan de verificatiecriteria voldoet.","de":"Die Rolle "verifiziertes Unternehmen" wird beim Abonnieren eines Abonnements zugewiesen, wenn das Unternehmen die Verifizierungskriterien erfüllt.","es":"La función "empresa verificada" se asigna al suscribirse a una suscripción si la empresa cumple con los criterios de verificación.","it":"Il ruolo di "società verificata" viene assegnato quando si sottoscrive un abbonamento se l\'azienda soddisfa i criteri di verifica.","ru":"Роль «подтвержденная компания» назначается при подписке на подписку, если компания соответствует критериям проверки.","pt":"A função "empresa verificada" é atribuída ao assinar uma assinatura se a empresa atender aos critérios de verificação."}','guard_name' => 'web','slug' => NULL,'created_at' => NULL,'updated_at' => '2019-01-26 19:22:20','deleted_at' => NULL),
                array('name' => 'developer','title' => '{"en":"Developer / Localization Specialist","fr":"Développeur / Spécialiste de la localisation","nl":"Developer / Localization Specialist","de":"Entwickler / Lokalisierungsspezialist","es":"Desarrollador / Especialista en localización","it":"Specialista di sviluppo / localizzazione","ru":"Разработчик / Специалист по локализации","pt":"Especialista em desenvolvimento / localização"}','description' => '{"en":"The developer role in the field of localization is granted to the creation of a developer account during the registration.","fr":"Le rôle de développeur spécialisé dans le domaine de la localisation est octroyé à la création d\'un compte de développeur lors de l\'enregistrement.","nl":"De ontwikkelaarrol op het gebied van lokalisatie wordt verleend aan het maken van een ontwikkelaarsaccount tijdens de registratie.","de":"Die Rolle des auf die Lokalisierung spezialisierten Entwicklers wird der Erstellung eines Entwicklerkontos während der Registrierung zugewiesen.","es":"El rol de desarrollador en el campo de la localización se otorga a la creación de una cuenta de desarrollador durante el registro.","it":"Il ruolo di sviluppatore specializzato nel campo della localizzazione è concesso alla creazione di un account sviluppatore durante la registrazione.","ru":"Роль разработчика в области локализации отводится созданию учетной записи разработчика при регистрации.","pt":"O papel do desenvolvedor especializado no campo da localização é concedido à criação de uma conta de desenvolvedor durante o registro."}','guard_name' => 'web','slug' => NULL,'created_at' => '2019-01-26 19:28:29','updated_at' => '2019-01-26 19:28:29','deleted_at' => NULL),
                array('name' => 'developer-verified','title' => '{"en":"Verified Developer / Localization Specialist","fr":"Développeur / Spécialiste de la localisation vérifié","nl":"Geverifieerde Developer / Localization Specialist","de":"Verifizierter Entwickler / Lokalisierungsspezialist","es":"Desarrollador / Especialista en localización verificado","it":"Sviluppatore / Specialista di localizzazione verificato","ru":"Проверенный разработчик / специалист по локализации","pt":"Especialista em desenvolvimento / localização verificado"}','description' => '{"en":"The role of specialized and verified developer in the field of localization is granted to the subscribing developers.","fr":"Le rôle de développeur spécialisé et vérifié dans le domaine de la localisation est octroyé à la souscription d\'un abonnement.","nl":"De rol van gespecialiseerde en geverifieerde ontwikkelaar op het gebied van lokalisatie wordt op abonnement toegewezen.","de":"Die Rolle des im Bereich der Lokalisierung spezialisierten und verifizierten Entwicklers wird zu geabonnierten Mitgliedern zugewiesen.","es":"El rol de desarrollador especializado y verificado en el campo de la localización se otorga a la suscripción de una suscripción.","it":"Il ruolo di sviluppatore specializzato e verificato nel campo della localizzazione è concesso alla sottoscrizione di un abbonamento.","ru":"Роль специализированного разработчика и проверена в области локализации предоставляется подписка на подписку.","pt":"A função de desenvolvedor especializado e verificado no campo da localização é concedido apos das verificaçãoes uteis."}','guard_name' => 'web','slug' => NULL,'created_at' => '2019-01-26 19:28:29','updated_at' => '2019-01-26 19:38:37','deleted_at' => NULL),
                array('name' => 'dtper-verified','title' => '{"en":"Verified DTP specialist","fr":"Infographiste / Spécialiste PAO vérifié","nl":"Geverifieerd grafisch ontwerper","de":"Verifizieter Grafikdesigner","es":"Diseñador gráfico verificado","it":"Specialista infografica verificato","ru":"Специалист по инфографике","pt":"Designer gráfico verificado"}','description' => '{"en":"The role of graphic designer is assigned at the time of registration, if the new user selects this option.","fr":"Le rôle d\'infographiste est assigné au moment de l\'enregistrement, si le nouvel utilisateur sélectionne cette option.","nl":"De rol van geverifieerd Grafisch ontwerper en DTP-specialistontwerper wordt op het moment van registratie toegewezen indien de nieuwe gebruiker deze optie selecteert.","de":"Geprüfter Grafikdesigner und DTP-Spezialist","es":"El rol de diseñador gráfico verificado se asigna en el momento del registro, si el nuevo usuario selecciona esta opción.","it":"Progettista grafico e specialista DTP verificato","ru":"Графический дизайнер и проверенный специалист DTP","pt":"A função de designer verificado gráfico é atribuída no momento do registro, se o novo usuário selecionar essa opção."}','guard_name' => 'web','slug' => NULL,'created_at' => NULL,'updated_at' => '2019-01-26 19:50:09','deleted_at' => NULL),
                array('name' => 'premium','title' => '{"en":"Premium","fr":"Premium","nl":"Premium","de":"Premium","es":"Premium","it":"Premium","ru":"Premium","pt":"Premium"}','description' => '{"en":"Premium User has been verified by the core team. It\'s a paid member.","fr":"L\'utilisateur Premium a fait l\'objet d\'une vérification par l\'équipe. C\'est un membre payant.","nl":"","de":"","es":"","it":"","ru":"","pt":""}','guard_name' => 'web','slug' => NULL,'created_at' => '2019-01-29 00:00:00','updated_at' => '2019-01-26 19:50:09','deleted_at' => NULL),
                array('name' => 'premium-exclusive','title' => '{"en":"Premium Exclusive","fr":"Premium Exclusive","nl":"Premium Exclusive","de":"Premium Exclusive","es":"Premium Exclusive","it":"Premium Exclusive","ru":"Premium Exclusive","pt":"Premium Exclusive"}','description' => '{"en":"Premium Exclusive User has been verified by the core team. It\'s a paid member.","fr":"L\'utilisateur Premium Exclusiv ea fait l\'objet d\'une vérification par l\'équipe. C\'est un membre payant.","nl":"","de":"","es":"","it":"","ru":"","pt":""}','guard_name' => 'web','slug' => NULL,'created_at' => '2019-01-29 00:00:00','updated_at' => '2019-01-26 19:50:09','deleted_at' => NULL),
                array('name' => 'proorg','title' => '{"fr":"Organisation professionnelle"}','description' => '{"en":"","fr":"","nl":"","de":"","es":"","it":"","ru":"","pt":""}','guard_name' => 'web','slug' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
                array('name' => 'academic','title' => '{"fr":"Intervenant académique"}','description' => '{"fr":"Intervenant académique"}','guard_name' => 'web','slug' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
                array('name' => 'translator','title' => '{"en":"Translator","fr":"Traducteur","nl":"Vertaler","de":"Übersetzer","es":"Traductor","it":"Traduttore","ru":"переводчик","pt":"Tradutor"}','description' => '{"en":"The unverified translator role, alias linguist, is assigned upon registration from the registration form.","fr":"Le rôle de traducteur alias linguiste, est assigné dès l\'inscription depuis le formulaire d\'enregistrement.","nl":"De rol van vertaler, alias linguïst, wordt toegekend bij registratie op het registratieformulier.","de":"Die Übersetzerrolle, Alias-Linguist, wird bei der Registrierung über das Registrierungsformular zugewiesen.","es":"El rol de traductor, alias lingüista, se asigna al registrarse desde el formulario de registro.","it":"Il ruolo di traduttore, alias linguista, viene assegnato al momento della registrazione dal modulo di registrazione.","ru":"Роль переводчика, псевдоним лингвиста, назначается при регистрации из регистрационной формы.","pt":"A função de tradutor, alias lingüista, é atribuída no registro do formulário de inscrição."}','guard_name' => 'web','slug' => NULL,'created_at' => NULL,'updated_at' => '2019-01-26 18:35:18','deleted_at' => NULL),
              )
        );** */
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        $tableNames = config('permission.table_names');

        Schema::drop($tableNames['role_has_permissions']);
        Schema::drop($tableNames['model_has_roles']);
        Schema::drop($tableNames['model_has_permissions']);
        Schema::drop($tableNames['roles']);
        Schema::drop($tableNames['permissions']);
    }
}
